version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: testeweb
      POSTGRES_PASSWORD: testeweb
      POSTGRES_DB: testeweb
    ports:
      - "5432:5432"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
