<?php 

$title = "Adicionando veiculo";

$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('veiculo', ['action' => 'adicionar']));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$placa = $this->form->get('placa');
$renavam = $this->form->get('renavam');
$modelo = $this->form->get('modelo');
$marca = $this->form->get('marca');
$ano = $this->form->get('ano');
$cor = $this->form->get('cor');

$placa->setAttribute('class', 'form-control');
$renavam->setAttribute('class', 'form-control');
$modelo->setAttribute('class', 'form-control');
$marca->setAttribute('class', 'form-control');
$ano->setAttribute('class', 'form-control');
$cor->setAttribute('class', 'form-control');
$placa->setAttribute('autofocus', 'autofocus');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formElement($id); ?>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($placa); ?>
        <?= $this->formElement($placa); ?>
        <?= $this->formElementErrors()->render($placa, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($renavam); ?>
        <?= $this->formElement($renavam); ?>
        <?= $this->formElementErrors()->render($renavam, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-8">
        <?= $this->formLabel($modelo); ?>
        <?= $this->formElement($modelo); ?>
        <?= $this->formElementErrors()->render($modelo, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-4">
        <?= $this->formLabel($marca); ?>
        <?= $this->formElement($marca); ?>
        <?= $this->formElementErrors()->render($marca, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-4">
        <?= $this->formLabel($ano); ?>
        <?= $this->formElement($ano); ?>
        <?= $this->formElementErrors()->render($ano, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-4">
        <?= $this->formLabel($cor); ?>
        <?= $this->formElement($cor); ?>
        <?= $this->formElementErrors()->render($cor, ['class' => 'help-block']); ?>
    </div>
</div>

<div class="row">
    <a href="<?= $this->url('veiculo', ['action' => 'index']) ?>" class="btn btn-warning">Voltar</a>
    <?= $this->formElement($submit); ?>
</div>