<?php 

$title = "Adicionando motorista";

$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title); ?></h1>

<?php
$form->setAttribute('action', $this->url('motorista', ['action' => 'adicionar']));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$nome = $this->form->get('nome');
$rg = $this->form->get('rg');
$cpf = $this->form->get('cpf');
$telefone = $this->form->get('telefone');
$veiculo_id = $this->form->get('veiculo_id');

$nome->setAttribute('class', 'form-control');
$rg->setAttribute('class', 'form-control');
$cpf->setAttribute('class', 'form-control');
$telefone->setAttribute('class', 'form-control');
$veiculo_id->setAttribute('class', 'form-control');

$nome->setAttribute('autofocus', 'autofocus');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formElement($id); ?>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($nome); ?>
        <?= $this->formElement($nome); ?>
        <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($rg); ?>
        <?= $this->formElement($rg); ?>
        <?= $this->formElementErrors()->render($rg, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-8">
        <?= $this->formLabel($cpf); ?>
        <?= $this->formElement($cpf); ?>
        <?= $this->formElementErrors()->render($cpf, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-4">
        <?= $this->formLabel($telefone); ?>
        <?= $this->formElement($telefone); ?>
        <?= $this->formElementErrors()->render($telefone, ['class' => 'help-block']); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-4">
        <?= $this->formLabel($veiculo_id); ?>
        <?= $this->formElement($veiculo_id); ?>
        <?= $this->formElementErrors()->render($veiculo_id, ['class' => 'help-block']); ?>
    </div>
</div>


<div class="row">
    <a href="<?= $this->url('motorista', ['action' => 'index']) ?>" class="btn btn-warning">Voltar</a>
    <?= $this->formElement($submit); ?>
</div>