<?php 

$title = "Marcadores no maps";

$this->headTitle($title);

?>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXB1iIUFtfpfuol_0Rxku6chABM1lpjOw"></script>

<h1><?= $title; ?></h1>

<div id="map" style="height: 400px;"></div>

<script>
    function initializeMap() {
        var mapOptions = {
            center: { lat: -23.550520, lng: -46.633308 },
            zoom: 12
        };
        var map = new google.maps.Map(document.getElementById('map'), mapOptions);

        // Adicionar marcadores
        var markers = <?= $veiculosJson ?>

        console.log(markers);
        
        markers.forEach(function (markerData) {
            var marker = new google.maps.Marker({
                position: markerData.position,
                map: map,
                title: markerData.title
            });

            var infoWindow = new google.maps.InfoWindow({
                content: markerData.content
            });

            marker.addListener('click', function () {
                infoWindow.open(map, marker);
            });
        });
    }

    google.maps.event.addDomListener(window, 'load', initializeMap);
</script>
