<?php 

$title = "Remover motorista";

$this->headTitle($title);

?>

<h1><?= $title; ?></h1>
<p>
    Você deseja realmente excluir "<?= $this->escapeHtml($motorista->getNome()); ?>"? 
</p>

<form method="post" action="<?= $this->url('motorista', ['action' => 'remover', 'id'=> $id]); ?>">
<div class="form-group">
    <input type="hidden" name="id" value="<?= $id ?>">
    <input type="submit" class="btn btn-danger" name="del" value="Sim">
    <input type="submit" class="btn btn-success" name="del" value="Não">
</div>

</form>
